label = "esperar"
text = "Claro, sem pressa. Volto em alguns minutos para pegar seu pedido."
image = "no_waiter.png"

[A]
label = "esperar"
text = "[Continue esperando...]"

[B]
label = "chamar_garcon"
text = "[Chame o garcon]"
