label = "sugestao"
text = "Nossa especialidade hoje é o risoto salmão. É excelente!"
image = "menu.png"

[A]
label = "end"
text = "Ok, vou pedir este mesmo."

[B]
label = "pedir_comida"
text = "Acho que vou pedir outra coisa do menu"
