label = "root"
text = "Boa noite! Bem-vindo ao nosso restaurante. Posso lhe oferecer o menu?"
image = "img/img.jpg"

[A]
label = "perdir_menu"
text = "Sim, por favor."

[B]
label = "pedir_bebida"
text = "Na verdade, estou aqui apenas para uma bebida no momento."

[C]
label = "esperar"
text = "Ainda não estou pronto para pedir. Pode me dar mais um momento?"

